title: Anna Esenther
description: Economics PhD Student at Harvard University
url: "https://annaesenther.com"
baseurl: ""

# Social media and contact
email: your.email@harvard.edu

# Build settings
markdown: kramdown
theme: minima

# Navigation
header_pages:
  - index.md
  - cv.md
  - teaching.md

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
